version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306"
    env_file:
      - docker.env

  db-test:
    image: mysql:8
    restart: always
    ports:
      - "3307"
    env_file:
      - docker.env

